# Import Necessary library

In [10]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

# 1.Data Collection

In [96]:
fraud = pd.read_csv('Fraud_check (1).csv')
fraud

Undergrad Marital.Status  Taxable.Income  City.Population  \
0          NO         Single           68833            50047   
1         YES       Divorced           33700           134075   
2          NO        Married           36925           160205   
3         YES         Single           50190           193264   
4          NO        Married           81002            27533   
..        ...            ...             ...              ...   
595       YES       Divorced           76340            39492   
596       YES       Divorced           69967            55369   
597        NO       Divorced           47334           154058   
598       YES        Married           98592           180083   
599        NO       Divorced           96519           158137   

     Work.Experience Urban  
0                 10   YES  
1                 18   YES  
2                 30   YES  
3                 15   YES  
4                 28    NO  
..               ...   ...  
595                7   YES  
596                2   YES  
597                0   YES  
598               17    NO  
599               16    NO  

[600 rows x 6 columns]

# 3.Data Understanding

In [5]:
fraud.shape

(600, 6)

In [6]:
fraud.isna().sum()

Undergrad          0
Marital.Status     0
Taxable.Income     0
City.Population    0
Work.Experience    0
Urban              0
dtype: int64

In [51]:
fraud.dtypes

Undergrad          object
Marital.Status     object
Taxable.Income      int64
City.Population     int64
Work.Experience     int64
Urban              object
dtype: object

# 4.Data Preparation

In [97]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
fraud['Undergrad']=le.fit_transform(fraud['Undergrad'])
fraud['Marital.Status'] = le.fit_transform(fraud['Marital.Status'])
fraud['Urban'] = le.fit_transform(fraud['Urban'])


In [98]:
for i in range (len(fraud['Taxable.Income'])):
    if fraud['Taxable.Income'][i] <= 30000:
        fraud['Taxable.Income'][i]= 'risky'
    else:
        fraud['Taxable.Income'][i] = 'good'

In [99]:
fraud['Taxable.Income'] = le.fit_transform(fraud['Taxable.Income'])

In [100]:
fraud

Undergrad  Marital.Status  Taxable.Income  City.Population  \
0            0               2               0            50047   
1            1               0               0           134075   
2            0               1               0           160205   
3            1               2               0           193264   
4            0               1               0            27533   
..         ...             ...             ...              ...   
595          1               0               0            39492   
596          1               0               0            55369   
597          0               0               0           154058   
598          1               1               0           180083   
599          0               0               0           158137   

     Work.Experience  Urban  
0                 10      1  
1                 18      1  
2                 30      1  
3                 15      1  
4                 28      0  
..               ...    ...  
595                7      1  
596                2      1  
597                0      1  
598               17      0  
599               16      0  

[600 rows x 6 columns]

In [80]:
fraud.dtypes

Undergrad          int32
Marital.Status     int32
Taxable.Income     int64
City.Population    int64
Work.Experience    int64
Urban              int32
dtype: object

In [101]:
fraud['Taxable.Income'].unique()

array([0, 1])

# 5.Model Building

In [102]:
X = fraud.drop('Taxable.Income',axis = 1)
y = fraud[['Taxable.Income']]

In [131]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.15,random_state=12,stratify=y)

In [132]:
X_train.shape,y_train.shape

((510, 5), (510, 1))

In [133]:
X_test.shape,y_test.shape

((90, 5), (90, 1))

# 6.Model Training

In [135]:
from sklearn.model_selection import GridSearchCV
gs = GridSearchCV(estimator = rf_classifier,param_grid= {'criterion':['gini','entropy'],
                                                        'max_depth':[2,3,4,5,6,7,8,9,10],
                                                        'n_estimators':[20,30,40,50,60,70,80,90,100]},cv =5)
grid = gs.fit(X,y)

In [122]:
grid.best_params_

{'criterion': 'gini', 'max_depth': 6, 'n_estimators': 20}

In [123]:
grid.best_score_

0.7949999999999999

In [136]:
from sklearn.ensemble import RandomForestClassifier
rf_classifier = RandomForestClassifier(criterion= 'gini', max_depth= 6, n_estimators= 20)
rf_classifier.fit(X_train,y_train)

RandomForestClassifier(max_depth=6, n_estimators=20)

# 7.Model Testing

##### Training data

In [125]:
y_pred_train = rf_classifier.predict(X_train)
y_pred_train

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,

##### Test data

In [126]:
y_pred_test = rf_classifier.predict(X_test)
y_pred_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

## 7. Model Evaluation

In [42]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,r2_score,confusion_matrix,roc_auc_score,classification_report

##### Training data

In [130]:
print('accuracy score:',accuracy_score(y_train,y_pred_train))
print('classification_report:\n',classification_report(y_train,y_pred_train))
print('confusion matrix:\n',confusion_matrix(y_train,y_pred_train))
print('roc_auc_score:',roc_auc_score(y_train,y_pred_train))

accuracy score: 0.7980392156862746
classification_report:
               precision    recall  f1-score   support

           0       0.79      1.00      0.89       397
           1       1.00      0.09      0.16       113

    accuracy                           0.80       510
   macro avg       0.90      0.54      0.52       510
weighted avg       0.84      0.80      0.73       510

confusion matrix:
 [[397   0]
 [103  10]]
roc_auc_score: 0.5442477876106194


##### Test data

In [129]:
print('accuracy score:',accuracy_score(y_test,y_pred_test))
print('classification_report:\n',classification_report(y_test,y_pred_test))
print('confusion matrix:\n',confusion_matrix(y_test,y_pred_test))
print('roc_auc_score:',roc_auc_score(y_test,y_pred_test))

accuracy score: 0.8666666666666667
classification_report:
               precision    recall  f1-score   support

           0       0.88      0.99      0.93        79
           1       0.00      0.00      0.00        11

    accuracy                           0.87        90
   macro avg       0.44      0.49      0.46        90
weighted avg       0.77      0.87      0.82        90

confusion matrix:
 [[78  1]
 [11  0]]
roc_auc_score: 0.4936708860759494


# Using Entropy criteria

In [138]:
rf_classifier_gini = RandomForestClassifier(n_jobs = 3,n_estimators = 15, oob_score = True, criterion = "entropy")
rf_classifier_gini.fit(X_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=15, n_jobs=3,
                       oob_score=True)

# 7.Model Testing

In [139]:
y_pred_train_gini = rf_classifier.predict(X_train)
y_pred_train_gini

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,

##### Test data

In [140]:
y_pred_test_gini = rf_classifier.predict(X_test)
y_pred_test_gini

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

## 7. Model Evaluation

In [42]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,r2_score,confusion_matrix,roc_auc_score,classification_report

##### Training data

In [142]:
print('accuracy score:',accuracy_score(y_train,y_pred_train_gini))
print('classification_report:\n',classification_report(y_train,y_pred_train_gini))
print('confusion matrix:\n',confusion_matrix(y_train,y_pred_train_gini))
print('roc_auc_score:',roc_auc_score(y_train,y_pred_train_gini))

accuracy score: 0.8117647058823529
classification_report:
               precision    recall  f1-score   support

           0       0.81      1.00      0.89       405
           1       1.00      0.09      0.16       105

    accuracy                           0.81       510
   macro avg       0.90      0.54      0.53       510
weighted avg       0.85      0.81      0.74       510

confusion matrix:
 [[405   0]
 [ 96   9]]
roc_auc_score: 0.5428571428571428


##### Test data

In [143]:
print('accuracy score:',accuracy_score(y_test,y_pred_test_gini))
print('classification_report:\n',classification_report(y_test,y_pred_test_gini))
print('confusion matrix:\n',confusion_matrix(y_test,y_pred_test_gini))
print('roc_auc_score:',roc_auc_score(y_test,y_pred_test_gini))

accuracy score: 0.7777777777777778
classification_report:
               precision    recall  f1-score   support

           0       0.79      0.99      0.87        71
           1       0.00      0.00      0.00        19

    accuracy                           0.78        90
   macro avg       0.39      0.49      0.44        90
weighted avg       0.62      0.78      0.69        90

confusion matrix:
 [[70  1]
 [19  0]]
roc_auc_score: 0.49295774647887325
